
<?php if (!empty($suggestion)): ?>

<section class="encounter mb-5">
    <div class="row">
        <div class="col-6">
            <img class="img-fluid" src="<?= $suggestion['avatar']; ?>">
            
            <div class="row">
                <div class="col-6">
                    <a class="btn btn-primary w-100" href="<?= $this->url('Encounter:Encounter@likeAction', array($suggestion['id'])); ?>"><?php $this->show('Like'); ?></a>
                </div>
                
                <div class="col-6">
                    <a class="btn btn-danger w-100" href="<?= $this->url('Encounter:Encounter@dislikeAction', array($suggestion['id'])); ?>"><?php $this->show('Dislike'); ?></a>
                </div>
            </div>
        </div>
    </div>
</section>

<?php else: ?>

<p><?php $this->show('No more matches for you at the time'); ?></p>

<?php endif; ?>